minecraft\:anvil=10
minecraft\:arrows=10
minecraft\:banners=10
minecraft\:barrels=10
minecraft\:barrels_wooden=10
minecraft\:beds=10
minecraft\:boats=20
minecraft\:bones=5
minecraft\:bookshelves=50
minecraft\:buttons=10
minecraft\:candles=10
minecraft\:carpets=10
minecraft\:chests=10
minecraft\:chests_ender=475
minecraft\:chests_trapped=10
minecraft\:chests_wooden=10
minecraft\:coal_ores=20
minecraft\:coals=20
minecraft\:cobblestone=5
minecraft\:cobblestone_deepslate=7
minecraft\:cobblestone_mossy=10
minecraft\:cobblestone_normal=5
minecraft\:copper_ores=50
minecraft\:crimson_stems=10
minecraft\:crops=10
minecraft\:diamond_ores=500
minecraft\:dirt=1
minecraft\:doors=10
minecraft\:dusts=120
minecraft\:dusts_glowstone=137
minecraft\:dusts_prismarine=250
minecraft\:dusts_redstone=137
minecraft\:dyes=10
minecraft\:dyes_black=15
minecraft\:dyes_blue=10
minecraft\:dyes_brown=10
minecraft\:dyes_cyan=10
minecraft\:dyes_gray=10
minecraft\:dyes_green=15
minecraft\:dyes_light_blue=10
minecraft\:dyes_light_gray=10
minecraft\:dyes_lime=10
minecraft\:dyes_magenta=10
minecraft\:dyes_orange=10
minecraft\:dyes_pink=10
minecraft\:dyes_purple=10
minecraft\:dyes_red=10
minecraft\:dyes_white=10
minecraft\:dyes_yellow=10
minecraft\:eggs=10
minecraft\:emerald_ores=400
minecraft\:enchanting_fuels=100
minecraft\:end_stones=150
minecraft\:ender_pearls=150
minecraft\:feathers=10
minecraft\:fence_gates=10
minecraft\:fence_gates_wooden=10
minecraft\:fences=10
minecraft\:fences_nether_brick=10
minecraft\:fences_wooden=10
minecraft\:fishes=10
minecraft\:flowers=5
minecraft\:gems=150
minecraft\:gems_amethyst=150
minecraft\:gems_diamond=500
minecraft\:gems_emerald=400
minecraft\:gems_lapis=250
minecraft\:gems_prismarine=250
minecraft\:gems_quartz=300
minecraft\:glass=10
minecraft\:glass_panes=20
minecraft\:glass_silica=20
minecraft\:glass_tinted=20
minecraft\:gold_ores=250
minecraft\:gravel=2
minecraft\:gunpowder=50
minecraft\:heads=100
minecraft\:ingots=15
minecraft\:ingots_brick=16
minecraft\:ingots_copper=55
minecraft\:ingots_gold=310
minecraft\:ingots_iron=110
minecraft\:ingots_nether_brick=20
minecraft\:ingots_netherite=750
minecraft\:iron_ores=110
minecraft\:lapis_ores=250
minecraft\:leather=50
minecraft\:leaves=2
minecraft\:lectern_books=100
minecraft\:logs=10
minecraft\:logs_that_burn=10
minecraft\:mushrooms=2
minecraft\:music_discs=10
minecraft\:nether_stars=900
minecraft\:netherrack=5
minecraft\:non_flammable_wood=10
minecraft\:nuggets=2
minecraft\:nuggets_gold=33
minecraft\:nuggets_iron=11
minecraft\:obsidian=400
minecraft\:ore_bearing_ground_deepslate=10
minecraft\:ore_bearing_ground_netherrack=10
minecraft\:ore_bearing_ground_stone=10
minecraft\:ores=10
minecraft\:ores_coal=25
minecraft\:ores_copper=50
minecraft\:ores_diamond=500
minecraft\:ores_emerald=400
minecraft\:ores_gold=300
minecraft\:ores_in_ground_deepslate=10
minecraft\:ores_in_ground_netherrack=10
minecraft\:ores_in_ground_stone=10
minecraft\:ores_iron=100
minecraft\:ores_lapis=250
minecraft\:ores_netherite_scrap=750
minecraft\:ores_quartz=300
minecraft\:ores_redstone=200
minecraft\:planks=10
minecraft\:rails=10
minecraft\:raw_materials=10
minecraft\:raw_materials_copper=50
minecraft\:raw_materials_gold=300
minecraft\:raw_materials_iron=100
minecraft\:redstone_ores=200
minecraft\:rods=50
minecraft\:rods_blaze=450
minecraft\:rods_wooden=10
minecraft\:sand=10
minecraft\:sand_colorless=10
minecraft\:sand_red=10
minecraft\:sandstone=15
minecraft\:saplings=2
minecraft\:seeds=2
minecraft\:shears=10
minecraft\:signs=10
minecraft\:slimeballs=40
minecraft\:small_flowers=10
minecraft\:soul_fire_base_blocks=100
minecraft\:stained_glass=10
minecraft\:stained_glass_panes=10
minecraft\:stone=5
minecraft\:stone_bricks=5
minecraft\:string=15
minecraft\:tall_flowers=5
minecraft\:terracotta=100
minecraft\:warped_stems=250
minecraft\:wooden_buttons=10
minecraft\:wooden_doors=60
minecraft\:wooden_fences=10
minecraft\:wooden_pressure_plates=20
minecraft\:wooden_slabs=30
minecraft\:wooden_stairs=60
minecraft\:wooden_trapdoors=60
minecraft\:wool=10
