name: PR

on:
  pull_request:
    branches: [ "1.16", "1.18", "1.19", "1.20", "1.21" ]
    paths:
      - 'src/**'
      - 'test/**'
      - build.gradle
      - gradle.properties
      - settings.gradle
      - .github/workflows/pr-build.yaml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version-file: .java-version
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 'wrapper'

      - name: Build and test
        run: |
          gradle build test --console=verbose
