name: PR

on:
  pull_request:
    branches: [ "1.16", "1.18", "1.19", "1.20", "1.21" ]
    paths:
      - 'src/**'
      - 'test/**'
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build and test
        run: |
          gradle build test --console=verbose
